// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJZsPoej-aMCsVqKKgiz_hUpoVH0VrJM',
    appId: '1:560060554313:web:c7004770f159c311413398',
    messagingSenderId: '560060554313',
    projectId: 'organic-market-pakistan',
    authDomain: 'organic-market-pakistan.firebaseapp.com',
    storageBucket: 'organic-market-pakistan.appspot.com',
    measurementId: 'G-68F7GE6D1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sMYj5hjRccV292pk0gc__AMT971O494',
    appId: '1:560060554313:android:2b807a7d7754e387413398',
    messagingSenderId: '560060554313',
    projectId: 'organic-market-pakistan',
    storageBucket: 'organic-market-pakistan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOC80R0Kqx8VS2KwXKrJ3DG927KKSc3DM',
    appId: '1:560060554313:ios:ecc4e0333c98b557413398',
    messagingSenderId: '560060554313',
    projectId: 'organic-market-pakistan',
    storageBucket: 'organic-market-pakistan.appspot.com',
    iosClientId: '560060554313-u4p1iik5h2k6lpe9f0n4fuhtgqllnaqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.organicMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOC80R0Kqx8VS2KwXKrJ3DG927KKSc3DM',
    appId: '1:560060554313:ios:ecc4e0333c98b557413398',
    messagingSenderId: '560060554313',
    projectId: 'organic-market-pakistan',
    storageBucket: 'organic-market-pakistan.appspot.com',
    iosClientId: '560060554313-u4p1iik5h2k6lpe9f0n4fuhtgqllnaqs.apps.googleusercontent.com',
    iosBundleId: 'com.example.organicMarket',
  );
}
